-- MySQL Script generated by MySQL Workbench
-- Thu Dec 26 14:48:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema oasa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oasa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oasa` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `idcategory` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `prize` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategory`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `idcategory_UNIQUE` (`idcategory` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `idclient` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `category_idcategory` INT NOT NULL,
  PRIMARY KEY (`idclient`, `category_idcategory`),
  UNIQUE INDEX `idclient_UNIQUE` (`idclient` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_client_category_idx` (`category_idcategory` ASC),
  CONSTRAINT `fk_client_category`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `mydb`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`line` (
  `idline` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idline`),
  UNIQUE INDEX `idline_UNIQUE` (`idline` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`station` (
  `idstation` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstation`),
  UNIQUE INDEX `idstation_UNIQUE` (`idstation` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `idticket` INT NOT NULL,
  `amount` VARCHAR(45) NULL,
  `category_idcategory` INT NOT NULL,
  PRIMARY KEY (`idticket`, `category_idcategory`),
  INDEX `fk_ticket_category1_idx` (`category_idcategory` ASC),
  CONSTRAINT `fk_ticket_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `mydb`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`line_has_station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`line_has_station` (
  `line_idline` INT NOT NULL,
  `station_idstation` INT NOT NULL,
  PRIMARY KEY (`line_idline`, `station_idstation`),
  INDEX `fk_line_has_station_station1_idx` (`station_idstation` ASC),
  INDEX `fk_line_has_station_line1_idx` (`line_idline` ASC),
  CONSTRAINT `fk_line_has_station_line1`
    FOREIGN KEY (`line_idline`)
    REFERENCES `mydb`.`line` (`idline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_line_has_station_station1`
    FOREIGN KEY (`station_idstation`)
    REFERENCES `mydb`.`station` (`idstation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
